USE data_pollutor;

INSERT INTO urls(url) VALUES
("www.google.com"),
("youtube.com"),
("apple.com"),
("microsoft.com"),
("play.google.com"),
("linkedin.com"),
("support.google.com"),
("www.blogger.com"),
("docs.google.com"),
("cloudflare.com"),
("mozilla.org"),
("maps.google.com"),
("en.wikipedia.org"),
("wordpress.org"),
("youtu.be"),
("europa.eu"),
("googleusercontent.com"),
("bp.blogspot.com"),
("sites.google.com"),
("whatsapp.com"),
("accounts.google.com"),
("adobe.com"),
("drive.google.com"),
("plus.google.com"),
("vimeo.com"),
("es.wikipedia.org");